
/*******************************************************************
* FeasyService.js
* Generated by Backendless Corp.
********************************************************************/

(function () {
  var serviceName = "FeasyService";
  var serviceVersion = "1.0.0";
  var appVersion = "v1";
  var appId = "AF27BD78-71F2-8608-FFE8-B321A0083F00";
  var secretKey = "27B58D04-CE23-A579-FFBD-A31B13136900";
  var serverURL = "http://feasy.westeurope.cloudapp.azure.com:80/api"

  Backendless.serverURL = serverURL;
  Backendless.initApp(appId, secretKey, appVersion);

  function FeasyService() {
    this.serviceVersion = serviceVersion;
    this.serviceName = serviceName;


    this.addCandidateToList = function (arg0, arg1, asyncObj) {
      //if (!(arg0 instanceof CandidateInfo))
      //  throw new Error("Invalid value for argument 'value'. Must be an CandidateInfo object");
      if (!Backendless.Utils.isString(arg1))
          throw new Error("Invalid value for argument 'value'. Must be string value");
      var args = {
        arg0: arg0,
        arg1: arg1
      };

      return Backendless.CustomServices.invoke(this.serviceName, this.serviceVersion, "addCandidateToList", args, asyncObj);
    };

  }

  this.FeasyService = new FeasyService();
})();
